# Generated by Django 3.1.1 on 2020-09-29 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(max_length=3000)),
                ('view_count', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='post/')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-id',),
            },
        ),
    ]
